[package]
name = "rusty-but-fast"
version = "0.1.0"
authors = ["Gabriel Francisco Mandaji <gfmandaji@gmail.com>"]
edition = "2018"

[lib]
test = true
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.4"
